//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antorena_Soto.CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Detalle_venta = new HashSet<Detalle_venta>();
        }
    
        public string nombre_prod { get; set; }
        public int codigo_prod { get; set; }
        public bool estado_prod { get; set; }
        public string descripcion_prod { get; set; }
        public int categoria_prod { get; set; }
        public double precio_prod { get; set; }
        public int stock_prod { get; set; }
        public byte[] imagen_prod { get; set; }
        public System.DateTime fechaModif_prod { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_venta> Detalle_venta { get; set; }
    }
}
