//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antorena_Soto.CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id_dni_usuario { get; set; }
        public string nomYApe_usuario { get; set; }
        public string provincia { get; set; }
        public string ciudad { get; set; }
        public string domicilio { get; set; }
        public long telefono { get; set; }
        public string correo { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public long cuit { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
    }
}
